//GET ALL CONTACT
export const GET_CONTACT_LOAD="GET_CONTACT_LOAD";
export const GET_CONTACT_SUCCESS="GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL="GET_CONTACT_FAIL";
//DELETE CONTACT
export const DELETE_CONTACT="DELETE_CONTACT";
//GET CONTACT BY ID
export const GET_CONTACT="GET_CONTACT";
//ADD CONTACT
export const POST_CONTACT="POST_CONTACT";
//EDIT CONTACT
export const EDIT_CONTACT="EDIT_CONTACT";